server:
  port: 9000

logging:
  level:
    org.springframework.security: trace

spring:
  application:
    name: authorization-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      format_sql: true
      show-sql: true
  security:
    user:
      name: user
      password: password